import React, { useState} from "react";
import axios from "axios";
import { useAuth } from "../../authContext";

import { PageHeader } from "@primer/react";
import { Box, Button } from "@primer/react";
import "./auth.css";

import logo from "../../assets/github-mark-white.svg";
import { Link } from "react-router-dom";

const Signup = () => { //
  // State variables for email, username, password, and loading state
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false); //temporary loading state to show loading text on button

  const { setCurrentUser } = useAuth(); //

  const handleSignup = async (e) => { //Button onClick//function to handle signup--async as it will make an API call--connect to backend and pass data of user email, username, and password
    e.preventDefault(); //prevent default loading of the page

    try { 
      setLoading(true);//page loading state set to true when user clicks on signup button
      const res = await axios.post("http://localhost:3002/signup", {
        email: email, //data provided by user in the form as an object passed to backend
        password: password,
        username: username,
      });

      localStorage.setItem("token", res.data.token); //save token in local storage generated by backend when user signs up
      localStorage.setItem("userId", res.data.userId); //save userId in local storage generated by backend when user signs up

      setCurrentUser(res.data.userId);
      setLoading(false); //set loading state to false when user successfully signed up

      window.location.href = "/"; //redirect to home page after successful signup
    } catch (err) {
      console.error(err);
      alert("Signup Failed!");
      setLoading(false);
    }
  };

  return (
    <div className="login-wrapper">

      <div className="login-logo-container">
        <img className="logo-login" src={logo} alt="Logo" />
      </div>

      <div className="login-box-wrapper">

        <div className="login-heading">
          <Box sx={{ padding: 1 }}>
            <PageHeader>
              <PageHeader.TitleArea variant="large">
                <PageHeader.Title>Sign Up</PageHeader.Title>
              </PageHeader.TitleArea>
            </PageHeader>
          </Box>
        </div>

        <div className="login-box">

          <div>
            <label className="label">Username</label>
            <input
              autoComplete="off"
              name="Username"
              id="Username"
              className="input"
              type="text"

              value={username}//
              onChange={(e) => setUsername(e.target.value)}//
            />
          </div>

          <div>
            <label className="label">Email address</label>
            <input
              autoComplete="off"
              name="Email"
              id="Email"
              className="input"
              type="email"

              value={email}//
              onChange={(e) => setEmail(e.target.value)}//
            />
          </div>

          <div className="div">
            <label className="label">Password</label>
            <input
              autoComplete="off"
              name="Password"
              id="Password"
              className="input"
              type="password"

              value={password}//
              onChange={(e) => setPassword(e.target.value)}//
            />
          </div>

          <Button
            variant="primary"
            className="login-btn"

            disabled={loading} //
            onClick={handleSignup}//
          >
            {loading ? "Loading..." : "Signup"}
          </Button>
        </div>

        <div className="pass-box">
          <p>
            Already have an account? <Link to="/auth">Login</Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Signup;
